config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  root "customers#index"
  get "/add-customer", to: "customers#new"
  post "/get-ajax-customer", to: "customers#ajaxCustomer"
  post "/add-customer", to: "customers#create"
  get "/show-customer/:id", to: "customers#show"





  get "/update-customer/:id", to: "customers#edit" , as: 'edit_customer'
  post "/update-customer", to: "customers#update"
  delete "/delete-customer/", to: "customers#delete"







  
  


  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    belongs_to :user
    validates :name, length: { minimum: 6 }
    validates :email,
              format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "Enter the valid email address."},
              :presence => {:message => "can't be blank." },
              :uniqueness => {:message => "already exists."}
    validates :phone, presence: true, format: {with: /\A[7-9][0-9]{9}\z/, message:"Enter the valid phone number."}
    validates :address, length: { minimum: 4 }
    validates :user_id, presence: true

    def self.search(search)
        where("name LIKE ?", "%#{search}%")
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :customers, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

    before_action :authenticate_user!

    def index
        @customer =current_user.customers.paginate(:page => params[:page],per_page: 10)
    end


    def ajaxCustomer
        
        if params[:dataOrdering]
            dataOrdering = params[:dataOrdering]
            dataOrderingSplitted = dataOrdering.split("-")
            customer = current_user.customers.order("#{dataOrderingSplitted[1]} #{dataOrderingSplitted[0]}")
            render :json => {:customerInfo => customer}
        end
        
        if params[:searchValue]
            searchValue = params[:searchValue]
            customer =  current_user.customers.search(searchValue)
            render :json => {:customerInfo => customer}

        end
    end


    def new
        #byebug
        @customer = Customer.new
    end


    def create
        #byebug
        @customer = Customer.new(customer_params)
        if @customer.save
            redirect_to root_path, notice: "Successfully created account !"
        else
            render 'new'
        end
    end

    def show
        @customer = current_user.customers.find_by(id: params.require(:id))
    end


    # ==========================================
    # Update

    def edit   
        @customer = current_user.customers.find_by(id: params.require(:id)) 
        if @customer.nil?
            flash[:alert] = 'Invalid customer!'   
            redirect_to root_path 
        end
    end  
    
    def update   
        #byebug
        @customer = Customer.find_by(id: params.require(:format))   
        if @customer.nil?
            flash[:alert] = 'Invalid customer!'   
            redirect_to root_path
        else
            if @customer.update_attributes(customer_params)   
            flash[:notice] = 'Customer details updated!'   
            redirect_to root_path   
            else   
            flash[:alert] = 'Failed to update details of customer!'   
            render :edit   
            end   
        end
    end

    # ==========================================
    # Delete


    def delete
        
        @customer = current_user.customers.find_by(id: params.require(:format))  
        @customer.destroy
        redirect_to(
          root_path,
          notice: 'Customer successfully deleted'
        )
    end

    # ==========================================


    private
    def customer_params 
        params.require(:customer).permit(:name, :email, :phone, :address, :user_id)
    end



    







end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/edit.html.erb
<div class="container mt-5 w-50 border p-5 shadow">

    <h1 class="add__customer__heading mb-4">Update Customer</h1>

    <%= form_for @customer, url:update_customer_path(@customer.id), html: { method: :post } do |form| %>


        <% if @customer.errors.any? %>
            <div class="alert alert-danger">
                <% @customer.errors.full_messages.each do |message| %>
                <div>
                    <%= message %>
                </div>
                <% end %>
            </div>
        <% end %>


        <div class="mb-3">
            <%= form.label :name %>    
            <%= form.text_field :name, class: "form-control", value: @customer.name %>
        </div>

        <div class="mb-3">
            <%= form.label :email %>    
            <%= form.text_field :email, class: "form-control", value: @customer.email %>
        </div>

        <div class="mb-3">
            <%= form.label :phone %>    
            <%= form.text_field :phone, class: "form-control", value: @customer.phone %>
        </div>
        <div class="mb-3">
            <%= form.label :address %>    
            <%= form.text_field :address, class: "form-control", value: @customer.address %>
        </div>



        <div class="w-100 text-center pt-3 d-flex justify-content-between align-items-center">
            <%= form.submit "Update Customer" ,class: "btn btn-primary ml-5" %>
            <a href=/show-customer/<%= @customer.id %> >Go Back </a>
        </div>

        <div class="text-left pt-3">
        
        </div>


    <% end %>


</div>

app/views/customers/index.html.erb
<div class="container mt-5">



<div class=" my-3 d-flex justify-content-between">
  <div>
    <%= link_to "Add Customer", add_customer_path, class: "btn btn-info"%>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <button class="btn btn-info">Add order </button>
  </div>
  
 
     
     <input type="text" class="searchCustName" placeholder="Search by customer name" />




</div>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
       <th scope="col">
        
        <div class=" w-75 d-flex justify-content-between align-items-center m-auto">

            <span>Sr. No</span>

            <div class="sorting__functionality">
              

              <i class="ajax-request fa-solid fa-arrow-up" data-ordering="asc-created_at"></i>
              <i class="ajax-request fa-solid fa-arrow-down" data-ordering="desc-created_at"></i>

              
            </div>

          </div>
        
      
      
      </th>
      <th scope="col">

           <div class=" w-50 d-flex justify-content-between align-items-center m-auto">

            <span>Name</span>

            <div class="sorting__functionality">
             
              <i class="ajax-request fa-solid fa-arrow-up" data-ordering="asc-name"></i>
             <i class="ajax-request fa-solid fa-arrow-down" data-ordering="desc-name"></i>




            </div>

          </div>
      
      
      </th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col" class="address__of">Address</th>
      <th scope="col">Order Count</th>

    </tr>
 
  </thead>
  
  <tbody class="customer__infomations">
    <% 
        pagenumber = params[:page].to_i  == 0 ? 1 : params[:page].to_i
        i = (pagenumber - 1).abs*10 + 1 
    %>
    <% @customer.each do |cust| %>

     <tr>
      <th scope="row"><%= i %></th>
      <td> <a href=/show-customer/<%= cust.id %>> <%= cust.name%> </a> </td>
      <td><%= cust.email %> </td>
      <td>+91-<%= cust.phone %> </td>
      <td class="address__of"><%= cust.address %> </td>
      <td>0</td>
    </tr>
      <% i=i+1 %>
    <% end %>
  
  </tbody>
</table>
<%= will_paginate @customer%>
</div>

app/views/customers/new.html.erb
<div class="container mt-5 w-50 border p-5 shadow">

    <h1 class="add__customer__heading mb-4">Add Customer </h1>

    <%= form_for @customer, url:add_customer_path do |form| %>


        <% if @customer.errors.any? %>
            <div class="alert alert-danger">
                <% @customer.errors.full_messages.each do |message| %>
                <div>
                    <%= message  %>
                </div>
                <% end %>
            </div>
        <% end %>




        <div class="mb-3">
            <%= form.label :name %>    
            <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= form.label :email %>    
            <%= form.text_field :email, class: "form-control"%>
        </div>

        <div class="mb-3">
            <%= form.label :phone %>    
            <%= form.text_field :phone, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :address %>    
            <%= form.text_field :address, class: "form-control"%>
        </div>

        <%= form.hidden_field :user_id, value:  current_user.id %>



        <div class="w-100 text-center pt-3 d-flex justify-content-between align-items-center">
            <%= form.submit "Add Customer" ,class: "btn btn-primary ml-5" %>
            <%= link_to "Go Back", root_path%>
        </div>

        <div class="text-left pt-3">
        
        </div>


    <% end %>


</div>

app/views/customers/show.html.erb
<div class="container mt-5 p-5 shadow">

    <div class="jumbotron">
        <h1 class="display-4"><%= @customer.name %></h1>
        <hr>
        <p class="lead"> <b>Email :</b> <%= @customer.email %></p>
        <p class="lead"> <b>Phone No :</b>+91-<%= @customer.phone %></p>
        <p class="lead"> <b>Address :</b> <%= @customer.address %></p>
        <hr>

        <div class="d-flex justify-content-between">
            <div class="d-flex justify-content-between">
                <a class="margin__right btn btn-success" href=/update-customer/<%= @customer.id %> >Edit</a>
                
                <%= link_to "Delete", delete_customer_path(@customer.id),method: :delete,data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

            </div>
     
            <%= link_to "Go Back", root_path , class: "btn btn-info"%>
        </div>
        <hr>
        <h3 class="recent__orders"> Recent Orders</h3>
        
       

        
    </div>


</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustomerOrderManagment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

<%= render 'shared/navbar'%>

  <%if notice%>

  <div class="container mt-5">
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>

  <%end%>
  <%if alert%>
  <div class="container mt-5">
     <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
  <%end%>


<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

app/views/shared/_navbar.html.erb
<header class="header__nav">

    <nav class="navbar__header">
        <h1><%= link_to "Customer Order Management", root_path %></h1>
    

    <div class="authenticaion__links">
        <% if user_signed_in? %>
        <span><i class="fa-solid fa-user"></i> &nbsp; <%= link_to "Hello, "+current_user.email, edit_user_registration_path %>&nbsp;</span>
        <span><i class="fa-solid fa-plus"></i> &nbsp; <a href="#">Add Products</a> &nbsp;</span>
        <span><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>&nbsp;&nbsp; <i class="fa-solid fa-right-from-bracket"></i></span>
        <% else %>
        <span><i class="fa-solid fa-right-to-bracket"></i> &nbsp;&nbsp;  <%= link_to "Sign In", new_user_session_path %> </span>
        <span><i class="fa-solid fa-user-plus"></i> &nbsp;&nbsp; <%= link_to "Sign Up", new_user_registration_path %></span>
        <% end %>
    </div>

    </nav>


</header>